### ISSUE TITLE
Unable to open filepaths that contain non-ASCII characters

### ISSUE THREAD

**Issue by KibayashiFuro2018** [Rosalie241/RMG#34]
Exactly as title says. If a rom is opened from a non-ASCII filepath (i.e. Japanese text), I get the error message:
　　EmulationThread::run Failed!
　　read_raw_file Failed: failed to open file!

Not sure if this is something that can be resolved, but it would certainly help if it did get resolved.

System specs are (in case the info is needed)
　CPU: AMD Ryzen 5 4600H with Radeon Graphics @ 3.00 GHz
　RAM: 8.00 GB
　Dedicated Graphics: NVIDIA GeForce GTX 165

![read_raw_file Failed](https://user-images.githubusercontent.com/39968751/160707607-0b3132e2-8419-4b43-a280-2572e7720918.png)

Hope this screencap helps.

**Comment by Kuro6804** [comment]
Having the same problem since I use ː as a substitute for colons in my file names.
![explorer_ZUI14VZgxL](https://user-images.githubusercontent.com/90160508/179016786-1b1a52bb-976e-44c3-8d91-57e169f81403.png)
![RMG_9iMQLK1ZLR](https://user-images.githubusercontent.com/90160508/179017150-dbeb976f-ae13-4d33-8e86-a83aafc21ca6.png)

**Comment by Rosalie241** [comment]
resolved with https://github.com/Rosalie241/RMG/actions/runs/3500238130, will be included in the next release.
