### ISSUE TITLE
[Feature Request] 7z support

### ISSUE THREAD

**Issue by AngryScotsmanGaming** [Rosalie241/RMG#63]
Will it be possible to implement .7z in the future? I like to keep all my files the same format to maintain them!

**Comment by Rosalie241** [comment]
That'll require using a different library for extracting archives, I'll keep it in mind but I'm not sure if/when I'll do that.

**Comment by Paelor** [comment]
Yeah, I also really wish RMG had 7z support. All the other Nintendo emulators that I use have 7zip support (bsnes, melonds, mesen-x, mgba) and would be nice to have everything in 7z rather than a mixture. I do hope that you change your mind down the road and add support for this, it's really my only gripe about RMG.

**Comment by mogarithm** [comment]
I would also like to express support for this feature request. 7zip is supported by other n64 emulators like simple64 and project64. Many users have their romsets stored in 7z format. This is the prime reason I have not yet adopted RMG as my main N64 emulator.

**Comment by Rosalie241** [comment]
I've implemented 7-zip support, please try this build and see if that works: https://github.com/Rosalie241/RMG/actions/runs/4623321717

**Comment by Rosalie241** [comment]
Thank you for testing, it'll be included in the next release then :two_hearts:

**Comment by Rosalie241** [comment]
Implemented in v0.3.9
